### ISSUE TITLE
Ability to create parent and child entries for Inventories

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#104]
## Describe the feature
We would like a way of linking inventories as they will often reappear various times throughout a manuscript, sometimes unchanged, and other times with new additions or subtractions. The individual inventories are not particularly meaningful, but how they change over time is. Therefore we would like a way of linking various versions of a transactions not just unilaterally but chronologically. We are very open to suggestion on how to best design this feature but my first thought was to create the earliest version of an inventory as a parent entry, with all subsequent versions of that inventory as child entries.

## How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?
This will allow us to present inventories in a way that is most effective in communicating meaningful information. As it is, we can create multiple inventories but the information remains disaggregated and consequently isn't very meaningful. Many inventories will appear as duplicates with different dates and page numbers. Separated, they look like a mistake in data entry, but when viewed in relation to other inventories they tell us that the inventory may not have changed for several years. This can lead to important research questions to figure out why this is the case.

Looking at the parish details page goes a long way to making the relationships of this data visible, but we want to make sure that these relationships are evident to researchers if they access inventories another way, or if they are viewing an individual inventory entry.

## Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?
I am having difficulty of thinking of alternatives but your suggestions are more than welcome! If you want to discuss this more we can certainly arrange a zoom meeting to brainstorm and clarify.

## Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.
URLs and/or screenshots for the examples, with a brief description of what we will see.

**Comment by ubermichael** [comment]
Hi Chelsea. I'll ask someone to set up a meeting to talk about this request and a couple of others.

**Comment by chelseakaylamarie** [comment]
Sounds great!
Cheers,
Chelsea
