### ISSUE TITLE
Include more information on the 'Inventory List'

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#118]
### Describe the feature

We would like data from the ‘Transcription’ field, ‘Modern English’ field, & ‘Page field’ visible to be visible on the ‘Inventory List’

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

This will streamline review and mistakes will be caught consistently.

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

If not implemented, reviewing the database will take longer and mistakes are more likely to escape notice.

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

See other fields visible on the Inventory List.

**Comment by ubermichael** [comment]
I have added the page information inside the source column of the table. But the transcription and modern english are too large to fit in an overview column.
