### ISSUE TITLE
Extend character limit on the "Page" field for Inventories

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#121]
### Describe the feature

We would like to extend the character limit for the "Page field for inventories so a longer string of data can be inputted. In cases where there is repeated data we note several page locations to indicate where each repeated inventory can be found in the manuscript without having to reproduce them in the database.

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

This will make it so we can note page numbers consistently rather than having to trunucate data to make it all fit.

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

If not implemented, researchers will be unaware of how many times an inventory is copied without changing.

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

N/A

**Comment by ubermichael** [comment]
The page field is now free text with 56745b4264bb498a3b22b809aa222923257072f0
