### ISSUE TITLE
Injunctions - Adding fields ("Nation”, “Diocese”, “Province”, and “Archdeaconry” Fields )

### ISSUE THREAD

**Issue by saba1995** [sfu-dhil/bep#125]
### Describe the feature

none of these will be required fields as usually only one of these will apply.
Note: Linked to existing provinces, archdeaconries, etc. in the database

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

NA

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

NA

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

NA

**Comment by chelseakaylamarie** [comment]
Can we prioritise this? We are hoping to start entering injunctions in the next few weeks!

**Comment by chelseakaylamarie** [comment]
Hello! Can we prioritise this one for the next week or so? We are eager to get started on entering the data for injunctions!

**Comment by chelseakaylamarie** [comment]
We are waiting for this field to be added so we can begin inputting data for injunctions. Please prioritise!
