### ISSUE TITLE
Add date field to 'Edit Monarch' page

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#139]
### Describe the feature

We would like start and end date fields for the monarch form. These would be regnal dates (not life dates of the individual) so it might be help to label them as such.

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

This will help with temporal mapping at later stages so dates can be related to monarchs.

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

If we don't implement this feature it will mean more work for the mapping stage of this project.

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

N/A

**Comment by ubermichael** [comment]
Would you like to include full dates (Feb 6, 1952) or just years (1952)?
