### ISSUE TITLE
Server slow down

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#142]
### What isn’t working as expected on the website?

The database was taking longer than normal to retrieve results and to load pages. (Approximately a minute or more for each page & auto-fill field). This began around 2:30PM on Sunday February 20th.

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

### What is the URL of the page where you encountered the bug?

https://dhil.lib.sfu.ca/bep/transaction/494/edit

### What steps did you take before you encountered the bug?

Open a new page or search for an autofill option. It would take a long time to load.

### What browser, operating system, and device were you using when you encountered the error?

Chrome

**Comment by ubermichael** [comment]
Seems to be working just fine now.
