### ISSUE TITLE
Add injunction field to Inventories form

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#161]
### Describe the feature

We'd like the injunctions field added to the Inventories form so we can capture relationships between the two.

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

This will enhance the future usefulness of this data to researchers.

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

N/A

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

See injunctions field in Transactions form.

**Comment by ubermichael** [comment]
I'm a little surprised by this one. Do the inventories mention injunctions in them?
