### ISSUE TITLE
Add ID Field to 'Inventory Details' Page

### ISSUE THREAD

**Issue by Bellamckenzie** [sfu-dhil/bep#163]
### Describe the feature

I'd like to see if we could add an ID field to the 'Inventory Details' page, so that the inventory number for specific entries will be displayed alongside the other relevant information. Thank you!

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

This feature will be helpful to both users and the project team. On the 'Transaction Details' pages, the field for the ID number is useful for data entry purposes and keeping track of progress, and it will be helpful for future users as they will be wanting to keep note of entries that are relevant to their research. Further, adding this feature will work to keep things uniform between the 'Transaction' and 'Inventory' categories. 

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

n/a

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

<img width="1345" alt="Screen Shot 2022-06-29 at 12 10 24 PM" src="https://user-images.githubusercontent.com/108429100/176517155-2dd36266-ae85-431c-ad1a-21d9222047d2.png">

**Comment by ubermichael** [comment]
fixed in ad49b85cc0c110b64ce7984156b962efa8b74bd4
