### ISSUE TITLE
Archdeaconry and other courts

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#17]
I've almost finished entering all of the archdeaconry courts.  I suggest that we call this field 'Archdeaconry and other courts'

Some counties had a range of what were called 'peculiar courts' - belonging to the Crown, or particular ecclesiastical officers, sometimes the lord of the manor.  
<img width="1243" alt="Screenshot 2021-01-08 at 21 20 49" src="https://user-images.githubusercontent.com/75693581/104065539-d2c79800-51f7-11eb-99d4-9c53ea3c1a20.png">

**Comment by ghost** [comment]
I will change it to read Archdeaconry & Peculiar Court.

How much useful would be to distinguish the courts and the archdeaconries? It's relatively simple to add a checkbox to say "This is a Particular Court" but I don't want to do that if it will make things more complicated than they need to be.
