### ISSUE TITLE
Transactions need dates - this is the most important issue 

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#24]
I've paid close attention to the various fields for entries under Transactions and they all make complete sense.

The most pressing issue needing attention is the lack of any dating.

All payments or receipts need to have dates attached as this will allow us, I hope, to do some searching of the data which is presently enormously cumbersome.

But dating is complex as the dates attached to each entry fall within a span and rarely land on a precise year, month or day.

I do have some rare entries that can be dated very precisely - day, month, year

But the overwhelming majority of entries will be dated between one accounting day in one year and another accounting day in another year - say 25 March 1569 - 25 March 1570.  

There will be other entries that have no dates and we need to make provision for this.

Here's a further complication - a good deal of our information comes from inventories which can be dated precisely - done on a certain day in a certain year, or at least done in a certain year.  But many of these lists were amended - entries struck through as books were sold, or lost or stolen.  Sometimes we can date these later emendations but often we cannot. Will the database be able to capture some of this uncertainty.  Is this the sort of information that goes into descriptive notes?

**Comment by joeytakeda** [comment]
(Not sure whether I should put this here or #26, so feel free to tell me to move this comment elsewhere!)

One thing we'll need to clarify for users is whether or not this is the date verbatim from the transcription or a normalized version of the date? 

This is especially important if we want to do any sort of temporal analysis like tracking the history of the book across the parishes. For example, say you have a book that has two records: on the transcription, it states it was sold February 1540 and then repaired in April 1541. If they're using the Julian calendar (they almost certainly would be, I would think), that would mean those two events are two months apart. However, in the database, if those two events are entered as February 1540 and April 1541 and we don't state whether these are Julian or Gregorian dates, then we're giving the impression that those two events occurred a year and two months apart.

If we can presume all of the dates are going to be using the same calendar, then I think those dates could be recorded either verbatim or normalized, so long as its consistent and clear. (Of course, if there's a mix of calendars--say if there's some emendation that is dated February 1701—and we want to record those dates as well, then it's even more complicated...)

**Comment by JSCraig** [comment]
Many thanks for this.  We do have consistency as far as the Julian/Gregorian divide is concerned. All our dates are with the Julian calendar.  England (Great Britain by this time) doesn't make the switch to Gregorian until 1752, so all our evidence (1536-1642) falls within the Julian calendar.  But as the new year started on 25 March, we have to be careful to watch any dates that land in Jan/Feb/March before the 25th as well as watching out for regnal years or accounting years.  Many of the London accounts make clear that they are recording evidence from one feast day in one year to another feast day in another year, but in more rural locations, some of this clarity is missing.

**Comment by ubermichael** [comment]
To summarize an email discussion

- Dates will go on each transaction.
- Dates will be normalized by @JSCraig and other researchers.
- Dates won't be transcribed.
- Dates will mostly be a date range, but may be a single date.
