### ISSUE TITLE
Injunctions - can we make the ESTC optional?

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#25]
Not all injunctions are found in the ESTC.  Some are only known from manuscript and modern printed sources.

For example, a three volume work by WH Frere and WPM Kennedy on Visitation Articles and Injunctions, published in 1910 has gathered a good deal of this information.  Currently I'm not able to include this information because much of what they found is not in the ESTC

**Comment by ubermichael** [comment]
The ESTC field is already optional. This one, for example, doesn't have an ESTC.

https://dhil.lib.sfu.ca/bep/injunction/1

**Comment by JSCraig** [comment]
Many thanks for this. Sorry for missing this.
J

Sent from my iPhone

On 18 Jan 2021, at 20:02, Michael Joyce <notifications@github.com<mailto:notifications@github.com>> wrote:


The ESTC field is already optional. This one, for example, doesn't have an ESTC.

https://dhil.lib.sfu.ca/bep/injunction/1
