### ISSUE TITLE
Dating of Books when we don't know the precise date - how has PLRE handled this?

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#26]
I thought it might be helpful to share the way in which Private Libraries in Renaissance England (PLRE) has arranged their data, all of it drawn from probate inventories - these are inventories drawn up following someone's death 

Their database supplies name, title, place of publication and a date range.  I'll show this for their entries with Wolfgang Musculus - a relatively common title found in a number of parishes
<img width="1434" alt="Screenshot 2021-01-14 at 12 38 44" src="https://user-images.githubusercontent.com/75693581/104592661-7553a100-5666-11eb-9106-7159132fa4a3.png">
<img width="1437" alt="Screenshot 2021-01-14 at 12 39 05" src="https://user-images.githubusercontent.com/75693581/104592671-78e72800-5666-11eb-848e-d90fff6af505.png">
<img width="1067" alt="Screenshot 2021-01-14 at 12 39 14" src="https://user-images.githubusercontent.com/75693581/104592690-80a6cc80-5666-11eb-989a-4902a1350f58.png">
<img width="1456" alt="Screenshot 2021-01-14 at 12 41 21" src="https://user-images.githubusercontent.com/75693581/104592704-856b8080-5666-11eb-8b67-e115aea97fab.png">
<img width="1084" alt="Screenshot 2021-01-14 at 12 42 07" src="https://user-images.githubusercontent.com/75693581/104592719-8ac8cb00-5666-11eb-9a50-f52411bb5672.png">

Perhaps the solution for our database is to show a date range when we don't know the precise date of any printed work - from the first possible printed version to the date of the manuscript entry

**Comment by ubermichael** [comment]
This would have been more useful as a comment in #24 John. We'll leave it as is right now, but for next time it's best to keep things more tightly organized.

**Comment by JSCraig** [comment]
Yes, I'm sorry about that.  I realised this too late and probably need to learn more about how best to lodge my comments...


I hope the geographical stuff - counties etc is not a headache... I have to join a meeting in a few minutes but am happy to discuss options with you - or is Slack the best thing..


J


John Craig, MA PhD FRHistS

Professor, Early Modern English History

Department of History

Simon Fraser University

8888 University Drive

Burnaby, BC CANADA

V5A 1S6



________________________________

**Comment by ubermichael** [comment]
There's some good information in the PLRE about how they go about determining the dates, and it could be a useful model for describing how BEP determines dates. But the way they store dates isn't quite as useful for us. They only store years, where we'll be doing more precise dates than that.
