### ISSUE TITLE
Revising Transactions to capture Inventories and Existing Books?

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#27]
I've been thinking more about the data entries under Transactions.  

There are two categories of data that don't fit so neatly into the existing data fields for Transactions and  wonder if there is a way to revise or create new fields for two significant bodies of data that we've collected from the manuscripts.

Let me start with the smaller body of data. These are the details of existing books found in various archives. In most cases we have no record of purchase or ownership but the actual text or a fragment of the text still survives.  In most of these cases, we can identify the text very precisely - author, title, publisher, date of publication, format and so forth, but as this isn't a transaction, we don't need any of the entries concerning payment or carriage, there is no transcript from any manuscript source and so forth.  I'll find an example and post it to this report.  

The second and more significant body of data that in a similar way doesn't fit into the transaction model we've created is the data gathered from lists of books or inventories of parish goods which included books. These are often found within churchwardens' accounts, or vestry books or were generated as separate documents.  Unlike lists of books found in probate inventories, these inventories have no values attached.  So once again, we have no entries concerning payments or carriage, but we do have a transcript from the manuscript entry and a date.  Unlike the data for payments, these lists take us directly to printed texts.  Complicating this evidence is that some urban parishes - London and Norwich parishes come to mind - routinely copied parish inventories at the end of each set of annual accounts.  And sometimes the only way to see how the collection of books changed is to compare one list with another. These changes are often quite difficult to date. The original lists almost always have a date for their composition.  It would be a great help to be able to enter the full transcript of a list of books and then identify individual books in these lists making clear the link to the whole list.

In light of these two distinct bodies of data, I'm wondering if it would be possible, before heading into the existing transaction fields, to provide two options - one for surviving books and the other for inventories, with both of these options taking the data entry clerk to slightly different fields reflecting the different character of the source material.

Here are some examples - the first from the parish of Haxey
<img width="1337" alt="Screenshot 2021-01-18 at 23 00 54" src="https://user-images.githubusercontent.com/75693581/104969683-1339c980-59e1-11eb-9924-0a845cca7582.png">
<img width="1344" alt="Screenshot 2021-01-18 at 22 59 07" src="https://user-images.githubusercontent.com/75693581/104969702-1df45e80-59e1-11eb-87b7-0c6f4cf46488.png">

I stopped entering partly because there was no separate field for date and partly because I felt there was a more efficient way to capture the data like this found in parish inventories.

Here's the other issue of actual books from the parish of Stubton in Lincolnshire:

<img width="1384" alt="Screenshot 2021-01-18 at 23 03 34" src="https://user-images.githubusercontent.com/75693581/104969842-7c214180-59e1-11eb-935a-4631f89d1fc0.png">

**Comment by ubermichael** [comment]
This one is now split out into #31 and #32.
