### ISSUE TITLE
Identifying Place of Purchase 

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#29]
We don't know much about how people bought printed books in the sixteenth century. Any evidence concerning where texts were actually bought or in some cases taken to be handed in becomes important. Is there some way to capture this.  I've gone through the data we've gathered from the parishes in Lincolnshire looking for this information. 

Books were carried to the towns of Boston and Lincoln.
Other books were bought at Stourbridge Fair (just outside Cambridge) or bought in London or Donington.

All this information will be found eventually in the Transactions and I suppose many of these entries will be identified through the Transaction Categories but what if we wished to map these locations?  Perhaps simply add them as other Parishes?  Or is there a better way?
<img width="1034" alt="Screenshot 2021-01-21 at 18 19 23" src="https://user-images.githubusercontent.com/75693581/105394702-d276c600-5c15-11eb-984c-e6a42f89535b.png">
<img width="1145" alt="Screenshot 2021-01-21 at 18 17 44" src="https://user-images.githubusercontent.com/75693581/105394707-d4408980-5c15-11eb-9877-7ed0430748ad.png">
<img width="1136" alt="Screenshot 2021-01-21 at 18 17 06" src="https://user-images.githubusercontent.com/75693581/105394709-d6a2e380-5c15-11eb-97aa-f6de7ec4d183.png">
<img width="1002" alt="Screenshot 2021-01-21 at 18 16 50" src="https://user-images.githubusercontent.com/75693581/105394721-d99dd400-5c15-11eb-8ac3-245d759215dd.png">

**Comment by ubermichael** [comment]
I can add a location field to the transaction record, that's easy enough. But will you also need more information about the location? I'm wondering about the difference between taking books **_to_** Lincoln vs getting books **_from_** Stirbridge faire.

**Comment by JSCraig** [comment]
If we have a description box for location fields, we could add text explaining what was taking place.

**Comment by JSCraig** [comment]
@ubermichael 
If we have a description box for location fields, we could add text explaining what was taking place.
