### ISSUE TITLE
Current Archive Holdings

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/bep#31]
**Is your feature request related to a problem? Please describe.**
We need to record the extant copies of the books in the parishes. Surviving copies of books purchased, etc.

**Describe the solution you'd like**
Add a new entity (name TBD) that records that a book is held by a parish, with the call number/accession number/identifer and a description of the book (missing first quire, some water damage, etc).

**Comment by ubermichael** [comment]
Maybe holdings as an entity name. Or holding. ParishHolding? It can't be inventory, since we will also have historical inventory records.

**Comment by ubermichael** [comment]
Description of the physical copy, call number/accession number.

**Comment by ubermichael** [comment]
Maybe also images? @JSCraig do you want to upload images or photographs of the books?

**Comment by JSCraig** [comment]
Yes. I'll need to get permission from the archivists but the option to upload images or photographs of the books would be great.
