### ISSUE TITLE
Adding optional Notes field to all Transaction entries

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#38]
Could we kindly add an optional notes field for all entries under Transactions?

This is what we currently have:  Transcription and Modern English
Screenshot in the comment below

**Comment by JSCraig** [comment]
Apologies - wrong screen shot:
<img width="1395" alt="Screenshot 2021-02-15 at 13 17 10" src="https://user-images.githubusercontent.com/75693581/107951645-91619f80-6f90-11eb-89e3-b3c7a160f624.png">

**Comment by ubermichael** [comment]
Would you also like to change Description to Modern English? That seems to be how you're using the description field.

**Comment by ubermichael** [comment]
Ah ha! I see that I changed Description to Modern English in the data entry form, but not in the display pages. So I'll just do that.
