### ISSUE TITLE
Book field - publisher entries- can we increase column length?

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#39]
In pulling data from the British Library's English Short Title Catalogue - ESTC, if the publishing data is too long, the database says no!

Here's an example from trying to include the full publishing data for Erasmus Paraphrases - second volume.  I made it work by cutting the publishing data but would prefer to include full data if possible:

<img width="1270" alt="Screenshot 2021-02-11 at 14 48 33" src="https://user-images.githubusercontent.com/75693581/107952090-354b4b00-6f91-11eb-9039-949101cb4dec.png">
<img width="1280" alt="Screenshot 2021-02-11 at 14 48 43" src="https://user-images.githubusercontent.com/75693581/107952118-41370d00-6f91-11eb-816f-44f88ab27806.png">

**Comment by JSCraig** [comment]
Here's the full data on the BL ESTC
<img width="849" alt="Screenshot 2021-02-11 at 14 54 09" src="https://user-images.githubusercontent.com/75693581/107952394-9d019600-6f91-11eb-9834-43f278b89252.png">

**Comment by ubermichael** [comment]
I'll make it a free text field. You can put as much text in it as you need.
