### ISSUE TITLE
Entries for Holdings List - Source needed; changing wording; dates; photographs

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#42]
There are a number of changes that need to be made here.

I don't think 'Holdings' is the right term.  I think it should be 'Surviving Texts'

Mostly, these are books, but in some instances they are printed texts on a single sheet of paper.

Currently, we have compulsory fields of Parish, Book, Description and Start Date.

We need to add the Source - that is the archive where these texts can be found.

I think it would be best to delete the compulsory date field and replace this with an optional date field in which we can enter the year of printing.  Yes, we sometimes have a more specific date for a particular printed text, but I suspect we won't have more than 50-60 surviving texts by the time the entire database is complete and a single year of printing/publication will be fine.
We had spoken about adding photographs to this section and I'm keen to do this.  I have photographs of many of these texts and we can get more.  Is this something we can do?

**Comment by ubermichael** [comment]
I think Date was meant to be the date that you or an assistant visited the parish and saw the book in situ. There's already a date field in the book records, so there's no need to replicate that in the holdings.

**Comment by ubermichael** [comment]
I'm a little confused with something. You'd like to add Source to the holdings (which will be renamed shortly) as the archive where the text can be found. But sources are the accounts books and other printed materials.

I think you mean to add Archive as a field in Holding. Can you please confirm that?

**Comment by JSCraig** [comment]
Yes, you are right.  I meant adding Archive as a field. All the Surviving Texts are held in specific Archives

**Comment by ubermichael** [comment]
> I think it would be best to delete the compulsory date field and replace this with an optional date field in which we can enter the year of printing. Yes, we sometimes have a more specific date for a particular printed text, but I suspect we won't have more than 50-60 surviving texts by the time the entire database is complete and a single year of printing/publication will be fine.

The best place for year of publication is in the book record, not in the surviving text record.
