### ISSUE TITLE
Parish coordinates

### ISSUE THREAD

**Issue by ghost** [sfu-dhil/bep#5]
Add a geographic coordinates field to the parishes for the parish church. Find a good way to display/map the coordinates.

**Comment by JSCraig** [comment]
I've started to add links either to wikipedia entries or to the Victoria County History  (VCH) volumes. The gold standard of local history in the UK is the VCH, but this project which first began in the 1880s or 1890s has dragged on and on and on.  But I'll show you from the Huntingdon entries what you can link to...
<img width="1331" alt="Screenshot 2021-01-08 at 21 17 20" src="https://user-images.githubusercontent.com/75693581/104065113-18379580-51f7-11eb-8a1c-a1190edcd8e7.png">
<img width="1003" alt="Screenshot 2021-01-08 at 21 18 01" src="https://user-images.githubusercontent.com/75693581/104065118-1c63b300-51f7-11eb-864f-4a17c1eaf7a8.png">
