### ISSUE TITLE
About - not able to add data

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#50]
When I try to create a page to enter data under the heading About, I'm told Page Not Found.
<img width="1158" alt="Screenshot 2021-03-05 at 11 35 25" src="https://user-images.githubusercontent.com/75693581/110110723-293ff580-7da7-11eb-84f0-09c253df228b.png">

**Comment by ubermichael** [comment]
There was some old test data in there that messed up the About pages. It's gone now.
