### ISSUE TITLE
Announcements - page not found when I click on this heading

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#51]
I've experimented with creating an announcement. Everything works.  But when I click on Announcements, I get 'Page Not Found.
<img width="1158" alt="Screenshot 2021-03-05 at 11 35 25" src="https://user-images.githubusercontent.com/75693581/110111396-2abded80-7da8-11eb-9a14-39a11d90e4f6.png">

**Comment by ubermichael** [comment]
Same as #50
