### ISSUE TITLE
Add date field to Injunctions

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#69]
Can we add a date field to Injunctions?

**Comment by ubermichael** [comment]
Will it be a full date or a year? Will there be any uncertainty in the date? Will you be using the date to sort entries?

**Comment by chelseakaylamarie** [comment]
Let's say it will just be a year. The dates should be certain and it would be lovely to be able to sort entries by year.

**Comment by ubermichael** [comment]
I have added an optional field called "Year" to injunctions.
