### ISSUE TITLE
Limited yield for search function on the Injunction List

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#71]
It looks like the search function in the Injunction List only searches the first word of the title. For example, it will find “1536 Royal Injunctions of Henry VIII” only if you search for “1536”, not if you search for “Royal” or “Henry”. Also, if I searched for terms in the description, no results were yielded.

Ideally we want it to function similarly to the search option for counties which searches the entirety of both the label & the description fields to yield relevant results.

**Comment by ubermichael** [comment]
title, description, and estc will all be searchable in the next update.
