### ISSUE TITLE
Transaction categories - Ability to select more than one

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#72]
Could we make it possible to select multiple transaction categories? For example, Transaction 00647 has been categorized as "Miscellaneous" due to the purchase of green ribbon but it should also be linked to "Purchase of Record Book". Also, would it be possible to make the transaction category a drop-down menu instead of the autofill? I think it would make it easier for new students doing the data entry. I think some might have been remembering a few options and mainly using those, though other categories would be a better fit. If they can see them all in one place without changing tabs I think that would improve accuracy.
![Picture1](https://user-images.githubusercontent.com/79331176/121760762-39235000-cae1-11eb-8749-9ece60257fed.jpg)

**Comment by chelseakaylamarie** [comment]
(My apologies on ignoring the question prompts! I'll use them going forward.)

**Comment by ubermichael** [comment]
Multiple categories for transactions won't be a problem. But there are 44 transaction categories, which could make the select box difficult to use.

**Comment by chelseakaylamarie** [comment]
I was thinking that too, lets stick with the autofill for now and I will encourage our data entry staff to have an additional tab open so they can see them all the options there.  But yes, let's move forward with the multiple categories.

**Comment by chelseakaylamarie** [comment]
Thank you! This looks amazing!
