### ISSUE TITLE
Ability to add "No date given" and format uncertain dates in the date field of transactions.

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#73]
**Is your feature request related to a problem? Please describe.**
We have some transactions that have no date or uncertain dates and we currently do not have a way to note that in the date field.

**Describe the solution you'd like**
I would love it if it was possible to enter "No Date" or uncertain dates instead of being limited to the numerical format. However, I will have to keep an eye on data entry to make sure it is consistent (So we don't end up with "unknown," "n.d," or irregularly formatted dates etc.).
Ideally it would be able to accommodate formats like:
Probable date: [1675?] 
Decade certain: [167-]
Approximate date: [ca. 1675] 
Probable decade: [167-?]

For example, one transaction says it was 'paide the 7 day of August 93' but we are uncertain if that is 1593 or 1693. Even so, 1593 is more probable.  Ideally I would like to be able to format it as [1593?]-08-07

**Describe alternatives you've considered**
An alternative option would be to have two boxes we could check for "No Date" and "Uncertain" which could deactivate the the regular date field. (So you could still save it). "No Date" would signify that no information is given, whereas "Uncertain" notes that there is information, but it is incomplete. 

**User Information**
This communicates to the user when we are lacking information or when they might need to look more closely at the transaction information.

**Additional context**

**Comment by ubermichael** [comment]
I think the best option would be to keep the current date field as is, and have a written date field where you can transcribe the date as recorded. You will be responsible for determining a "normalized" version of the date which would be used for sorting and searching, but the written date field would be text.

**Comment by chelseakaylamarie** [comment]
That sounds great!

**Comment by ubermichael** [comment]
I made the change to holdings, inventories, and transactions because they all use the same date handling code.

**Comment by chelseakaylamarie** [comment]
Thank you for adding this! Instead of formatting it as 'Written as "..."' when saved could we change it to 'Additional Information:'?

This field will likely be used most often to note when there is no date present, in which case 'Written as "No date"' can be confusing.

Instead it might be clearer if it said "Additional Information: No date." If we wanted to transcribe something we could write it as "Additional Note: Written as "3rd of May '93""
