### ISSUE TITLE
Possible to enter "Unknown" for Copies field

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to be able to enter "Unknown" as an option for number of copies. I found a transaction in which someone willed 'a cartload of books' to the parish. It is evidently more than one or two, but the actual number is unknown.

**Describe alternatives you've considered**
An alternative could be a box to check by the 'copies' field labelled 'unknown'.

**User Information**
This ensures that transactions with an uncertain number of books are not catalogued as "0" or otherwise.

**Additional context**

**Comment by ubermichael** [comment]
It's best to leave the copies field empty in this case. There was a bug with an empty null field, but that will be corrected at the next update.

**Comment by chelseakaylamarie** [comment]
Wonderful, thank you!
