### ISSUE TITLE
Additional fields for book

### ISSUE THREAD

**Issue by ghost** [sfu-dhil/bep#8]
Publisher and printer field may be useful for books.

**Comment by JSCraig** [comment]
Yes, I'll try to find some examples where we have this level of detail. Being able to specify particular editions of texts produced by specific printers will be of great interest to bibliographers and historians.  Most of our entries will not have this level of detail.

**Comment by ubermichael** [comment]
Should Edition be a number field (1, 2, 3) or a text field (First edition, First English Edition), or both? There may be value in having both of those, but it's really a question for you @JSCraig

**Comment by JSCraig** [comment]
I'll give a fuller response perhaps later today - my general thought is that we should revise the fields to reflect the way in which information is set out in the ESTC

**Comment by JSCraig** [comment]
I've been thinking through the Book Details and comparing our fields with those found in the ESTC.  We certainly don't need to replicate all the information found in the ESTC but I do feel that we need to have the following fields, or separate entries and would be grateful if they could be added:

Author
Uniform Title (for works translated from an original Latin or French text)
Publisher
Year - to replace existing Date
ESTC

Here's an illustration comparing the 1616 edition of James I, A Remonstrance.
<img width="1489" alt="Screenshot 2021-01-18 at 21 18 01" src="https://user-images.githubusercontent.com/75693581/104964153-c4d1fe00-59d3-11eb-9345-c4f2c6b5308a.png">
<img width="1009" alt="Screenshot 2021-01-18 at 21 20 28" src="https://user-images.githubusercontent.com/75693581/104964158-c8fe1b80-59d3-11eb-8ead-9db1626350f5.png">
<img width="1009" alt="Screenshot 2021-01-18 at 21 20 28" src="https://user-images.githubusercontent.com/75693581/104964171-cf8c9300-59d3-11eb-9215-ad0103c60e33.png">

**Comment by JSCraig** [comment]
@ubermichael 

Suggest the following fields for Books - with the addition of 4 new fields

Author - new field
Uniform Title (for works translated from an original Latin or French text) - new field
Title
Variant Titles
Publisher - new field
Date
Description
ESTC - new field
Format

Drop the suggestion above that we have a separate field for Edition
