### ISSUE TITLE
A Public Notes field for Transactions.

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#83]
**Is your feature request related to a problem? Please describe.**
Right now we only have an internal notes section for Transaction entries so we don't have a way of communicating important information to the public such as "This folio was water damaged, therefore portions are this transaction are illegible," or "This transaction is related to Transaction 474."

**Describe the solution you'd like**
We would like to have both a public "Notes" field & an "Internal Notes" field for transaction entries.

**Describe alternatives you've considered**
N/A

**User Information**
This helps us communicate important information to the public while also having a field for internal notes.

**Additional context**
N/A

**Comment by ubermichael** [comment]
Hi Chelsea. I think I'm a little confused by this one. The title says a new public notes field, but the solution mentions a public field and a private field.

Also, how will this public notes field be different from the description field? Both are public, and both serve more or less the same function.

**Comment by chelseakaylamarie** [comment]
Hello Michael! Sorry for the confusion.
On transaction entries there is currently no 'description' field. We have the Transcription, Modern English, and a 'Notes' field which is currently for internal use only.
I would like to have a set up similar to what we have for inventories where there is a private notes field and a public notes field. 

The private notes field is for communicating among ourselves if something is unclear or if more work needs to be done before the transaction is completed. 

The public notes section allows us to note the context or to describe the physical appearance of the transaction. For example, if the edge of the page has been ripped, we can note that the cost is incomplete or missing due to a missing piece of the folio it is written on. This is different from the transcription or modern English sections because we are not noting down text that is actually there. We are adding context and interpretation. Nevertheless this is information that should be communicate to the public, not just kept as internal notes.

Hopefully this helps! Let me know if you need more clarification.

**Comment by chelseakaylamarie** [comment]
Thank you!
